"""
#* Mutitasking in python:- Exectuting multiple tasks at a time.

two types of multitasking :- 1. process based multitasking
2. thread based multitasking.

#* what is thread and its need and applications?
- A thread is operating system object which executes instructions / program.
- A thread is a separate flow of execution in program.

to achieve threading python provide built-in module "threading".
threads are python objects of threading.Thread() class.
"""

import threading

# print(threading.current_thread().name)
# print(threading.current_thread().ident)
# print(threading.current_thread().is_alive())

# how to create thread there are 4 steps:- 
# 1. import thread class

# from threading import Thread, current_thread

# # 2. Create a function containing code to be executed parallaly.
# def display(n, msg):
#     print('t1 thread details: ', current_thread())
#     for i in range(n):
#         print(msg)

# # 3. Create a new thread

# t1 = Thread(target= display, kwargs={'n': 4, 'msg':'har har mahadev'})
# t1.start()   #this is executed by t1 thread


# for i in range(3):   #this code is executed by main thread
#     print("Sushil is python developer")




# How to create thread for methods
# from threading import Thread

# class Test:
#     def display(self, n):
#         for i in range(n):
#             print(f"Congratulations Sushil for getting 'Software engineer' Job!")

# obj = Test()
# t1 = Thread(target= obj.display, args=(5,))
# t1.start()

# for i in range(5):
#     print("I'm so grateful for all this success.")
    







# How to create thread by extending thread class:-
from threading import Thread
import time

tasks = ['Exercising', 'Cold shower', 'Meditation', 'Reading', 'Coding', 'Learning and developing']


# class MyThread(Thread):
#     def __init__(self, val):
#         print("Constructor called")
#         self.adult = val
#         Thread.__init__(self)
    
#     def run(self):
#         if self.adult:
#             for task in tasks:
#                 print(f"Working on {task} task")
#                 time.sleep(3)
#                 print(f"{task} completed!")
#         else:
#             print("Baby just play and do fun")
#         self.take_rest()
            
#     def take_rest(self):
#         print("Take some rest champ")
    
# m1 = MyThread(True)
# m1.start()

# for i in range(6):
#     time.sleep(0.5)
#     print("Doing task")


"""
*Biggest advantage of using this way of creating threads ?
*=>You can access data generated by threads
"""

# from threading import Thread

# def display():
#     global result
#     a = 10 
#     b = 1
#     result = a + b

# t = Thread(target=display)
# t.start()
# print(result)



#How to configure thread names and what are threading identity numbers:- 

from threading import Thread, current_thread

def display():
    for i in range(3):
        print("Sushil happily got dreamjob as a 'Software Engineer'")

def show():
    for i in range(6):
        print("Sushil is most richest, smart , intellectual Software Engineer.")

# t1 = Thread(target=display)
# t1.start()
# t2 = Thread(target=show)
# t2.start()

# to get name of thread u can use:-
# print(t1.name)
# print(t2.name)

#u can change value of thread also
# t1.name = "Sushil"
# print(t1.name)


#*You can change main thread name also for that it requires object of main thread
#* you can access main thread by import current_thread

# current_thread().name = "Sheetal"
# print(current_thread().name)




# Thread identifier :- 
# Each identifier has a unique identifier (id) within python process.


from threading import Thread

def show():
    for i in range(9):
        print("I'm the first ever crorepati in my entire blood.")

# t = Thread(target=show)
# t.start()
# print(t.ident)
# print(t.native_id)


# import os
# you can get program id for each program
# print(os.getpid())







"""
*Suppose ur working on multithreading and you want to know current running thread
*and details of all thread.

Here's way

there are some built in functions provided by python:-

is_alive():- Checks thread is running or not

main_thread():- Returns main thread details 

active_count() :- Number of running thread

enumerate() :- list of all running thread

get_native_id():- know native id of thread

"""




# from threading import Thread, main_thread, active_count, enumerate, get_native_id

# def display():
#     print("Native id of t1 thread: ", get_native_id())
#     print("Main thread details: ",main_thread().name)
#     for i in range(5):
#         print("I've fullfilled all the dreams and desires of my mom and dad.")

# t1 = Thread(target=display)
# print("before",t1.is_alive())
# t1.start()
# print(get_native_id())
# # print('Numbers of threads: ', active_count())
# print('Numbers of threads: ', enumerate())
# print("after",t1.is_alive())
